### ISSUE TITLE
[Question] Free Proxies

### ISSUE THREAD

**Issue by Looooopy** [suuhm/docker-unblock-proxy#1]
Do you have any free proxy's that you recommend for Netflix and Disney?

**Comment by suuhm** [comment]
It depends on which country you want to spoof / or hide. But to find the best proxies you can just use google-search like "free proxies list" , "free elite proxies" or just try ```-e NGINE=squid```

**Comment by Looooopy** [comment]
Ok thanks, it was US or UK, I would look into it.

I have been using https://www.smartdnsproxy.com/ (it works) the DNS version and not VPN but its only free for 2 weeks that's why I would like to try your solution.

Squid can you elaborate what does it do, I suppose it is a DNS Server used for my clients, but what happens under the hood and how does the other engines compare to each other?

**Comment by suuhm** [comment]
Squid , redsocks or proxychains all have basically the same goal to read the poxies from the proxies.lst. But there can be minor differences in speed and encryption. You can have a closer look here: https://github.com/suuhm/unblock-proxy.sh
Squid is a little bit more complex, because it uses privoxy and certificate creation under the hood. and with proxychains you can use multiple proxies in a row for example.

**Comment by Looooopy** [comment]
Thanks!
